### PR TITLE
Eliminate as many `any` as possible

### PR DESCRIPTION
**Pull request by sarvaje**

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje can you fix the conflicts?

**Comment by sarvaje** [comment]
@molant sure thing!

**Comment by sarvaje** [comment]
@molant done!

**Comment by austinkelleher** [comment]
Just by looking at this diff, it looks like somehow @molant's commit for #295 got into here since something strange happened with the original merge. Not sure if this was intended or not.

**Comment by sarvaje** [comment]
@austinkelleher It wasn't intended (AFAIK) may be something happens doing a rebase

**Comment by molant** [comment]
@sarvaje, you have some conflicts :(

**Comment by alrra** [comment]
>  some conflicts :(

Fixed the conflicts, removed [the unneeded commit](https://github.com/sonarwhal/sonar/pull/296/commits/4c6f14fee526f9ac550659f4514ab6ddd8216e40), and merged the PR with some modifications in 65528ed3bbb368ca20bb46c3d3f8a08ae35a2234.

**Pull request closed without merging**
