### PR TITLE
Refactor cdp to share code with edge diagnostics adapter

### PR DESCRIPTION
**Pull request by sarvaje**

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje I'm thinking that maybe this should happen in two steps so we don't hold the changes for too long:

1. Refactor all the CDP code to make it easier to add support for edge and Firefox later. This should include #311
2. Support for new collectors

Thoughts? You can create a new issue for the refactor to keep track.

**Comment by sarvaje** [comment]
For me it is ok, but what about the code that there is already about edge adapter?

**Comment by molant** [comment]
Don't commit those changes in that PR and you can rebase once it's merged

**Comment by sarvaje** [comment]
PR created with refactor and `chrome launcher`.
Closing this PR!

**Pull request closed without merging**
