### PR TITLE
Chore: Add greenkeeper-lock

### PR DESCRIPTION
**Pull request by molant**
Fix: #433

### CODE REVIEW

**Comment by alrra** [comment]
This doesn't work, see for example: https://github.com/sonarwhal/sonar/pull/513.

**Comment by molant** [comment]
@alrra did this got merged? By looking at the [changes](https://github.com/sonarwhal/sonar/pull/509/files) it looks like not...

**Comment by alrra** [comment]
> did this got merged before? By looking at the changes it looks like not...

[Yes](https://github.com/sonarwhal/sonar/commit/a43fb6ec4bb0f3d0812c2f7322028322ebb4d63c).

**Comment by alrra** [comment]
I'm opening the issue, and closing this PR.

**Pull request closed without merging**
