### PR TITLE
Build: Make TypeScript enforce `LF` newlines

### LINKED ISSUE #564: Remove system-specific carriage returns
Looks like there's a Window's specific carriage return goofing things up on my Mac: 

```
Rachels-MacBook-Pro-2:reloaded rachel$ sonar
env: node\r: No such file or directory
```

## Environment
Mac, running NVM. Am unable to create `.sonarrc`.

* __`Node.js` version: v8.6.0
* __`npm` version: 5.3.0

### PR DESCRIPTION
**Pull request by alrra**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonar)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/developer-guide/contributing/pull-requests.html#commitmessages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

From https://www.typescriptlang.org/docs/handbook/compiler-options.html:

> --newLine: Use the specified end of line sequence to be used when emitting files: 'crlf' (windows) or 'lf' (unix). "

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fix #564 

@molant Please test this, and confirm it works! Thanks!

### CODE REVIEW

**Comment by molant** [comment]
@alrra this doesn't work on my machine. I had to update `package.json` with `"build:ts": "tsc --outDir dist --newLine lf"` to get the right end line. Trying to figure out if `newLine` is actually a valid option in `tsconfig.json`

**Comment by molant** [comment]
Opened an issue in the TypeScript project: https://github.com/Microsoft/TypeScript/issues/18966

@alrra do we want to update just the `build:ts` command for now so I can still publish?

**Comment by alrra** [comment]
> do we want to update just the build:ts command for now so I can still publish?

Yes, update my PR and merge it! Thanks!

**Comment by molant** [comment]
Issue was with wehere `newLine` was in `tsconfig.json`. More info in https://github.com/Microsoft/TypeScript/issues/18966#issuecomment-334551861

**Pull request merged**
