### PR TITLE
Docs: Update Code of Conduct links

### PR DESCRIPTION
**Pull request by kborchers**
Link to CoC on JS Foundation website to ensure it is always up to
date and includes the full CoC including the committee,
enforcement details, etc.

### CODE REVIEW

**Comment by alrra** [comment]
> Link to CoC on JS Foundation website to ensure it is always up to

@kborchers How often is that changed? 

---

See also: https://github.com/sonarwhal/sonar/pull/353

**Comment by kborchers** [comment]
@alrra It's not change often if ever but we also don't track all of these other versions so if it does change, your would be outdated. More importantly, the CoC includes a number of other pages with more information about the committee, enforcement of the code, etc that it is important people read as well so by linking directly to the JSF version, there is no question if people were given the full CoC to review.

**Comment by alrra** [comment]
@kborchers Maybe keep the `CODE_OF_CONDUCT.md` file and just add a link in to https://js.foundation/community/code-of-conduct?

**Comment by kborchers** [comment]
Not sure that's absolutely necessary since the CoC is linked in the README but if the team prefers that, I'm fine with it.

**Comment by alrra** [comment]
> Not sure that's absolutely necessary since the CoC is linked in the README but if the team prefers that, I'm fine with it.

@sonarwhal/contributors ?

**Comment by qzhou1607** [comment]
Linking directly seems okay to me when I first tried it out, but I'm not sure if it is best practice to link to pages in other domain from the navigation bar. Also if we do decide to link directly, maybe we can consider redirecting https://sonarwhal.com/about/code_of_conduct.html to https://js.foundation/community/code-of-conduct so that 404 won't show?

**Comment by alrra** [comment]
My concern: The `CODE_OF_CONDUCT.md` file has become something of a "standard" file and, [like GitHub](https://github.com/sonarwhal/sonar/pull/353), I've seen other tools searching for it and signaling the lack of a code of conduct when they don't find it.

> maybe we can consider redirecting https://sonarwhal.com/about/code_of_conduct.html to https://js.foundation/community/code-of-conduct so that 404 won't show? 

[Yes](https://github.com/sonarwhal/sonarwhal.com/issues/192#issuecomment-324694270).

**Comment by alrra** [comment]
Also when opening a new issue, now we get:



instead of:

**Comment by kborchers** [comment]
I think getting the conduct link back is important so I would say we should add `CODE_OF_CONDUCT.md` back and in the file just say something like

The sonar project follows the [JS Foundation Code of Conduct](https://js.foundation/community/code-of-conduct)

**Comment by dmethvin** [comment]
That seems like the best solution to me as well. Any bots that want to see the file will be satisfied, but you won't have to duplicate the CoC.

**Comment by alrra** [comment]
> I think getting the conduct link back is important so I would say we should add CODE_OF_CONDUCT.md back and in the file just say something like
>
> The sonar project follows the JS Foundation Code of Conduct

>That seems like the best solution to me as well. Any bots that want to see the file will be satisfied, but you won't have to duplicate the CoC.

Done in https://github.com/sonarwhal/sonar/commit/ca849a3f9ad5fa4572e43034aae117fc817b907a.

**Comment by alrra** [comment]
Note: Also updated the other projects: [1](https://github.com/sonarwhal/sonarwhal.com/commit/e40e571b26dcffbd6d094beca6c1514f0cf1c254), [2](https://github.com/sonarwhal/online-service/commit/f95e6b39bedb05995fd0bfb0587611674f2450f4), and [3](https://github.com/sonarwhal/connector-edge15/commit/715f8f642b23be1f3002c2214e70f9fac8547d4d).

**Pull request merged**
